# 乱数

In [1]:
import numpy as np

In [2]:
# 0から1の浮動小数点数
np.random.rand()

0.8572970473126136

In [3]:
# nparrayもOK
np.random.rand(3, 2)

array([[0.50560867, 0.43909079],
       [0.38801771, 0.82617289],
       [0.06896812, 0.70387018]])

In [4]:
np.random.rand(5)

array([0.64200745, 0.71369652, 0.55220873, 0.71018328, 0.80754017])

In [10]:
# 整数型の乱数
np.random.randint(4)

3

In [11]:
np.random.randint(10, 20)

10

In [14]:
np.random.randint(5, size=(3, 3))

array([[2, 1, 1],
       [0, 4, 1],
       [2, 0, 2]])

## 再現性と乱数の種

In [15]:
def throw_dice(n):
    return np.random.randint(1, 7, size=n).sum()

In [16]:
throw_dice(10)

34

In [17]:
throw_dice(10)

30

In [21]:
np.random.seed(10)
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [22]:
np.random.seed(10)
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [23]:
def throw_dice(n, random_seed=10):
    np.random.seed(random_seed)
    return np.random.randint(1, 7, size=n).sum()

In [24]:
throw_dice(10)

34

In [25]:
throw_dice(10)

34

In [40]:
# よくない実装例
# コンストラクタで乱数の種を設定しているので、取得される乱数の値が同じになってしまう
class Dice:
    def __init__(self):
        np.random.seed(0)
        self.sum_ = 0
        
    def throw(self):
        self.sum_ += np.random.randint(1, 7)
        
    def get_sum(self):
        return self.sum_

In [47]:
d1 = Dice()

In [28]:
for _ in range(10):
    d1.throw()

In [29]:
d1.get_sum()

39

In [48]:
d2 = Dice()

In [31]:
for _ in range(10):
    d2.throw()

In [32]:
d2.get_sum()

39

In [52]:
for _ in range(10):
    d1.throw()
    d2.throw()

In [53]:
d1.get_sum()

69

In [54]:
d1.get_sum()

69

In [33]:
# コンスタラクタの引数に種を与えると結果に再現性がある例
class Dice:
    def __init__(self, random_seed=None):
        self.random_state_ = np.random.RandomState(random_seed)
        self.sum_ = 0
    
    def throw(self):
        self.sum_ += self.random_state_.randint(1, 7)
    
    def get_sum(self):
        return self.sum_

In [34]:
d1 = Dice(123)

In [35]:
d2 = Dice(123)

In [36]:
for _ in range(10):
    d1.throw()
    d2.throw()

In [37]:
d1.get_sum()

34

In [38]:
d2.get_sum()

34