# NumPyの基本

In [1]:
import numpy as np

## 基本

In [2]:
np.exp(2)

7.38905609893065

In [5]:
np.log(np.e)

1.0

In [6]:
np.sin(np.pi)

1.2246467991473532e-16

In [7]:
np.sqrt(3)

1.7320508075688772

## NumPyの配列

In [8]:
a = np.array([2, 3, 5, 7, 8])

In [9]:
a[0]

2

In [10]:
a[1:3]

array([3, 5])

In [12]:
a[2:-1]

array([5, 7])

In [13]:
b = np.arange(5)

In [14]:
b

array([0, 1, 2, 3, 4])

In [15]:
c = np.arange(1, 3, 0.2)

In [16]:
c

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [17]:
a.dtype

dtype('int64')

In [18]:
c.dtype

dtype('float64')

In [20]:
d = np.array([1, 2, 3], dtype=np.float64)

In [21]:
d.dtype

dtype('float64')

In [22]:
e = np.arange(5.)

In [23]:
e

array([0., 1., 2., 3., 4.])

In [24]:
e.dtype

dtype('float64')

## 2次元配列

In [25]:
a = np.array([[2, 3, 4], [5, 6, 7]], dtype=np.float64)

In [26]:
a

array([[2., 3., 4.],
       [5., 6., 7.]])

In [28]:
a[0, 1]

3.0

In [29]:
a[:, 1]

array([3., 6.])

In [30]:
a[1, :]

array([5., 6., 7.])

In [32]:
a[0, 2:]

array([4.])

In [33]:
a[0, :2]

array([2., 3.])

In [36]:
# 1次元配列
v = np.array([2., 3., 4.])

# 2次元配列
a = np.array([[1., 2.], [3., 4.]])

## 配列のデータ属性

In [37]:
a = np.arange(15.).reshape(3, 5)

In [38]:
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [41]:
# 配列の形状
a.shape

(3, 5)

In [42]:
# 配列の次元数
a.ndim

2

In [43]:
# 配列の要素数
a.size

15

In [44]:
b = np.arange(4.)

In [45]:
b.shape

(4,)

In [46]:
b.ndim

1

In [47]:
b.size

4

## reshapeメソッドと形状の変更

In [48]:
a = np.arange(16.)

In [49]:
c = a.reshape(4, -1)

In [50]:
c

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [51]:
# 1次元配列に戻す
c.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [52]:
a.flatten()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [53]:
c.reshape(-1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [54]:
b = np.arange(4.)

In [57]:
b

array([0., 1., 2., 3.])

In [55]:
b.reshape(-1, 1)

array([[0.],
       [1.],
       [2.],
       [3.]])

In [56]:
b[:, np.newaxis]

array([[0.],
       [1.],
       [2.],
       [3.]])

In [59]:
b[:, None]

array([[0.],
       [1.],
       [2.],
       [3.]])

In [60]:
b.reshape(1, -1)

array([[0., 1., 2., 3.]])

In [61]:
b[np.newaxis, :]

array([[0., 1., 2., 3.]])

## その他の配列の操作

In [65]:
a = np.zeros((3, 4))

In [66]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
b = np.ones((2, 2))

In [68]:
b

array([[1., 1.],
       [1., 1.]])

In [69]:
c = np.empty((2, 5))

In [70]:
c

array([[1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8]])

In [71]:
d = np.linspace(0, 1, 10)

In [72]:
d

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## 行列の連結

In [75]:
a = np.array([[0, 1, 2], [3, 4, 5]])

In [76]:
b = np.array([[6, 7, 8], [9, 10, 11]])

In [77]:
# 縦方向に連結
np.r_[a, b]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
np.concatenate((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [80]:
# 横方向に連結
np.c_[a, b]

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [81]:
c = np.arange(3)

In [82]:
d = np.arange(3, 6)

In [83]:
c

array([0, 1, 2])

In [84]:
d

array([3, 4, 5])

In [85]:
np.r_[c, d]

array([0, 1, 2, 3, 4, 5])

In [86]:
np.c_[c, d]

array([[0, 3],
       [1, 4],
       [2, 5]])