# 線形代数

In [5]:
import numpy as np
from scipy import linalg

In [3]:
# 逆行列
a = np.array([[3, 1, 1], [1, 2, 1], [0, -1, 1]])
np.linalg.inv(a)

array([[ 0.42857143, -0.28571429, -0.14285714],
       [-0.14285714,  0.42857143, -0.28571429],
       [-0.14285714,  0.42857143,  0.71428571]])

In [4]:
# １次方程式
a = np.array([[3, 1, 1], [1, 2, 1], [0, -1, 1]])
b = np.array([1, 2, 3])

np.linalg.solve(a, b)

array([-0.57142857, -0.14285714,  2.85714286])

In [6]:
# LU分解
a = np.array([[3, 1, 1], [1, 2, 1], [0, -1, 1]])
b = np.array([1, 2, 3])

# LU分解の実行
lu, p = linalg.lu_factor(a)
linalg.lu_solve((lu, p), b)

array([-0.57142857, -0.14285714,  2.85714286])