# 配列の基本計算

In [2]:
import numpy as np

## 集計

### 1次元配列

In [3]:
a = np.arange(5.)

In [4]:
a.sum()

10.0

In [5]:
a.mean()

2.0

In [7]:
a.max()

4.0

In [8]:
a.min()

0.0

### ２次元配列

In [9]:
b = np.arange(9.).reshape(3, -1)

In [10]:
b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [11]:
b.sum()

36.0

In [12]:
b.sum(axis=0)

array([ 9., 12., 15.])

In [13]:
b.sum(axis=1)

array([ 3., 12., 21.])

## ブロードキャスト

In [14]:
a = np.arange(3., 8.)

In [15]:
a

array([3., 4., 5., 6., 7.])

In [16]:
np.exp(a)

array([  20.08553692,   54.59815003,  148.4131591 ,  403.42879349,
       1096.63315843])

In [17]:
np.log(a)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015])

In [18]:
np.sqrt(a)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131])

In [19]:
b = np.arange(9.).reshape(3, -1)

In [20]:
b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [21]:
np.exp(b)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [22]:
a = np.arange(5)

In [23]:
a

array([0, 1, 2, 3, 4])

In [24]:
a + 3

array([3, 4, 5, 6, 7])

In [25]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [26]:
a >= 2

array([False, False,  True,  True,  True])

In [27]:
a != 3

array([ True,  True,  True, False,  True])

In [29]:
b = np.arange(9).reshape(3, -1)

In [30]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
b > 3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [32]:
b = np.empty(a.shape[0])

In [33]:
b

array([4.65135617e-310, 0.00000000e+000, 1.58101007e-322, 0.00000000e+000,
       0.00000000e+000])

In [34]:
for i, x in enumerate(a):
    b[i] = x ** 2

In [35]:
b

array([ 0.,  1.,  4.,  9., 16.])

In [36]:
a = np.arange(10)

In [37]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a[a > 5]

array([6, 7, 8, 9])

In [39]:
a[(a >= 3) & (a < 6)]

array([3, 4, 5])

In [41]:
a[a % 3 == 0]

array([0, 3, 6, 9])

## 配列の演算

In [42]:
u = np.arange(4)

In [43]:
v = np.arange(3, 7)

In [44]:
u

array([0, 1, 2, 3])

In [46]:
v

array([3, 4, 5, 6])

In [48]:
u + v

array([3, 5, 7, 9])

In [49]:
u - v

array([-3, -3, -3, -3])

In [50]:
# 内積
np.dot(u, v)

32

In [53]:
(u * v).sum()

32

In [54]:
u @ v

32